basePath: /api/v1
definitions:
  handler.CreateOpeningRequest:
    properties:
      company:
        example: Google
        type: string
      link:
        example: https://google.com/careers/123
        type: string
      location:
        example: Remote
        type: string
      remote:
        example: true
        type: boolean
      role:
        example: Backend Developer
        type: string
      salary:
        example: 120000
        type: integer
    type: object
  handler.CreateOpeningResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.OpeningResponse'
      message:
        example: operation create-opening successful
        type: string
    type: object
  handler.DeleteOpeningResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.OpeningResponse'
      message:
        example: operation delete-opening successful
        type: string
    type: object
  handler.ErrorResponse:
    properties:
      errorCode:
        example: 400
        type: integer
      message:
        example: error message
        type: string
    type: object
  handler.ListOpeningsResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/schemas.OpeningResponse'
        type: array
      message:
        example: operation list-openings successful
        type: string
    type: object
  handler.ShowOpeningResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.OpeningResponse'
      message:
        example: operation show-opening successful
        type: string
    type: object
  handler.UpdateOpeningRequest:
    properties:
      company:
        example: Google
        type: string
      link:
        example: https://google.com/careers/456
        type: string
      location:
        example: Lisbon, Portugal
        type: string
      remote:
        example: true
        type: boolean
      role:
        example: Senior Backend Developer
        type: string
      salary:
        example: 150000
        type: integer
    type: object
  handler.UpdateOpeningResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.OpeningResponse'
      message:
        example: operation update-opening successful
        type: string
    type: object
  schemas.OpeningResponse:
    properties:
      company:
        example: Google
        type: string
      createdAt:
        example: "2024-01-01T00:00:00Z"
        type: string
      deletedAt:
        type: string
      id:
        example: 1
        type: integer
      link:
        example: https://google.com/careers/123
        type: string
      location:
        example: Remote
        type: string
      remote:
        example: true
        type: boolean
      role:
        example: Backend Developer
        type: string
      salary:
        example: 120000
        type: integer
      updatedAt:
        example: "2024-01-01T00:00:00Z"
        type: string
    type: object
info:
  contact:
    name: Jo√£o Pedro Lira
    url: https://github.com/lirajoaop/gopportunities
  description: API to manage job opportunities, including creating, listing, updating,
    and deleting job openings.
  title: Go Opportunities API
  version: "1.0"
paths:
  /openings:
    get:
      consumes:
      - application/json
      description: Get all job openings
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ListOpeningsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: List all openings
      tags:
      - Opening
    post:
      consumes:
      - application/json
      description: Create a new job opening
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.CreateOpeningRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.CreateOpeningResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Create opening
      tags:
      - Opening
  /openings/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a job opening by ID
      parameters:
      - description: Opening ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.DeleteOpeningResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Delete opening
      tags:
      - Opening
    get:
      consumes:
      - application/json
      description: Get a job opening by ID
      parameters:
      - description: Opening ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ShowOpeningResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Show opening
      tags:
      - Opening
    put:
      consumes:
      - application/json
      description: Update a job opening by ID
      parameters:
      - description: Opening ID
        in: path
        name: id
        required: true
        type: string
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateOpeningRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.UpdateOpeningResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Update opening
      tags:
      - Opening
schemes:
- http
- https
swagger: "2.0"
